apiVersion: v1
kind: Service
metadata:
  labels:
    app: grpcstore-demo
    discovery.solo.io/function_discovery: enabled
  name: grpcstore-demo
  namespace: default
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: grpcstore-demo
